from collections import namedtuple

Consultas = namedtuple('Consultas',['consulta','tabela','limite'])

# Consultas no SQL Server para gerar arquivos parquet
sql_queries =   [
                    Consultas(consulta='select ID, ID_CLI, COD_PROD, ID_PROD, CEAN, DESCRICAO, EX_PROD, EX_BENEF, NCM, NCM_SUGERIDA, NCM_DUVIDA, STATUS_INTEGRACAO, STATUS, CADASTRO_OK, convert(varchar(10),VIGENTE_DE,120) as VIGENTE_DE, convert(varchar(10),VIGENTE_ATE,120) as VIGENTE_ATE, SEM_PRODUTO, EX_TIPI, ID_GRUPO, LISTA_ID_TIPO, ID_MARCA, ID_EMBALAGEM, QTD, PRED_ALIQ, CLASSE_BEBIDA, CONTROLE, convert(bigint,TS) as ts, PROD_PADRAO, convert(varchar(10),DT_CRIACAO,120) as DT_CRIACAO, QUESTIONAMENTO, ORIGEM_PRODUTO, CEAN_ORIGINAL, QUEST_CONFIG, CEAN_REVISADO, STATUS_MED, EAN_LISTA, MEDICAMENTO_LISTA, MEDICAMENTO_TIPO, FLAG_VINCULACAO_ESPECIAL, REVISAO_INFO, CADASTRO_FISCAL_OK, convert(varchar(10), DH_ENTREGA_CADASTRO_FISCAL,120) as DH_ENTREGA_CADASTRO_FISCAL, NCM_EX_SUGESTAO, FLAG_BASE_NAO_USAR, FLAG_MEDICAMENTO, CEAN14_MED, TIPO_VINCULACAO, FLAG_FORA_AGRUPAMENTO_PROD, FLAG_MULTIPLICACAO_ORIGEM, CEAN14, 1 as STATUS_ATIVO, convert(bigint, ts) as PONTEIRO_ATUALIZACAO from systax_app.dbo.custom_prod order by id;',  tabela='custom_prod',limite=50000000),
                    Consultas(consulta='select ID, ID_GRUPO, ID_TRIB_INTER_CONFIG, ID_CLI, convert(bigint,TS) as TS, 1 as STATUS_ATIVO, convert(bigint, ts) as PONTEIRO_ATUALIZACAO  from systax_app.dbo.grupo_config (nolock) order by id;',  tabela='grupo_config',limite=10000000),
                    Consultas(consulta='select ID, ID_GRUPO, ID_CUSTOM_PROD, ID_CLI, convert(bigint, TS) as TS, 1 as STATUS_ATIVO, convert(bigint,TS) as PONTEIRO_ATUALIZACAO from systax_app.dbo.grupo_custom_prod (nolock) order by id;',  tabela='grupo_custom_prod',limite=100000000),
                    Consultas(consulta='select ID, ID_CLIENTE, APELIDO, GRUPO_CACHE, COD_NAT_OP, DESTINACAO, UF_ORIGEM, UF_DESTINO, CNPJ_EX_ORIGEM, COD_PROD_EXEMPLO, DATA_RECALCULAR, FLAG_EXEC, ALTERNATIVO_EX_ORIGEM, ID_CLIENTE_PROD, ID_CLIENTE_CONFIG_PROD, FREQUENCIA, ID_MUN_ORIGEM, ID_MUN_DESTINO, DIAS_FUTUROS, ID_CONFIG_PRINCIPAL, ID_CONFIG_ICMS, ID_CONFIG_IPI, ID_CONFIG_PIS, ID_CONFIG_COFINS, ID_CONFIG_ANTECIPACAO, PRIORIDADE, ID_CONFIG_MANUAL_PIS, ID_CONFIG_MANUAL_COFINS, ID_CONFIG_MANUAL_IPI, ID_CONFIG_MANUAL_ANTECIPACAO, CNAE_DESTINATARIO, GRUPO_STR, ID_CONFIG_SETOR, ENT_SAI, ID_REL_FUTURO, FINALIDADE, TOTAL_PRODUTOS, TOTAL_PRODUTOS_CALCULADOS, FLAG_DESCONSIDERAR, ORIGEM_PRODUTO_ALTERNATIVO, CENARIO_IND_PROD, ID_PROD_ADIC, ST_CEST, convert(varchar(10), DT_CRIACAO, 120) as DT_CRIACAO, ORIGEM_CRIACAO, FLAG_HOMOLOG, TRIB_CIGARRO_CALCULO, CRIACAO_AUTOMATICA, FLAG_REVISAO, FLAG_ORIGEM_ESCRITURACAO, CENARIO_INATIVO, 1 as STATUS_ATIVO, convert(bigint, 0) as PONTEIRO_ATUALIZACAO from systax_app.dbo.tributos_internos_cache_config (nolock) order by id;',  tabela='tributos_internos_cache_config',limite=100000000),
                    Consultas(consulta='select id, id_config, tributo, clientes_vinculados, convert(varchar(10), data_criacao, 120), ponteiro, id_atualizacao_admin from systax_app.dbo.impact_client (nolock) order by id;',  tabela='impact_client',limite=100000000),
                    Consultas(consulta='SELECT id , id_custom_prod , id_atualizacao_admin , cod_prod ,	origem_produto, ncm , ex_tipi , id_produto , convert(varchar(10), data_criacao, 120) as data_criacao, ponteiro from systax_app.dbo.impact_products (nolock) order by id;',  tabela='impact_products',limite=100000000),
                    Consultas(consulta='select id_custom_prod_padrao, id_config_setor from systax_app.dbo.tmp_cruzamento_vigde02 t (nolock);',  tabela='tmp_cruzamento_vigde02',limite=100000000),    
                    Consultas(consulta='select id, local_regra, uf_regra, uf_destino, id_tributo, ncm, ex_tipi, dispositivo_legal, id_produto, campo_alterado, segmento, convert(varchar(10), vigencia_de, 120) as vigencia_de, convert(varchar(10), vigencia_ate, 120) as vigencia_ate, convert(varchar(10), data_criacao, 120) as data_criacao, ponteiro from systax_regras.dbo.atualizacao_admin (nolock) order by id;',  tabela='atualizacao_admin',limite=100000000),    
                ]
    